name 'httpd'
maintainer 'IACHYDG3'
maintainer_email 'iachydg3@gmail.com'
license 'All rights reserved'
description 'Installs/Configures httpd'
long_description 'Installs/Configures httpd'
version '1.0.1'
source_url 'https://github.com/IACHYDG3/httpd'
issues_url 'https://github.com/IACHYDG3/httpd/issues'

depends 'httpd'
depends 'hc_yum'
depends 'logrotate'
depends 'iptables'
