# Generated by: Chefspec_maker
# This Chefspec was generated automatically and requires human attention!!!

require 'spec_helper'

describe 'httpd::load_mods_config' do
  context 'default' do
    let(:chef_run) do
      ChefSpec::SoloRunner.new(platform: 'oracle', version: '6.6') do |node|
        node.normal['httpd']['conf_mod_dir'] = 'httpd_conf_mod_dir'
        node.normal['httpd']['mod_loads'] = %w(mod1 mod2)
      end.converge('httpd::default', described_recipe)
    end

    before do
      stub_command('chkconfig sssd').and_return(true)
    end

    %w(mod1 mod2).each do |mod|
      it "creates config for #{mod}" do
        expect(chef_run).to create_httpd_config("#{mod} conf")
      end
    end

    it 'writes log added mod configuration for specified mods' do
      expect(chef_run).to write_log('added mod configuration for specified mods')
    end
    # notification?
  end
end
